### ISSUE TITLE
Finish implementing local-state-query

### ISSUE THREAD

**Issue by agaffney** [cloudstruct/go-ouroboros-network#44]
The messages and protocol state machine were added in #10, but there are no helper functions, test programs, or query/result handling.

**Comment by Titan-C** [comment]
Hi, I have recently worked on the query/result specification of this protocol. I published it on https://arsmagna.xyz/docs/network-lsq/
I hope it assists you well before you go to reverse engineering the Haskell code as I did.

**Comment by wolf31o2** [comment]
It definitely helps. Thank you.

**Comment by agaffney** [comment]
@Titan-C Your doc was definitely helpful while implementing this support. Thank you

**Comment by agaffney** [comment]
Additional resources:

* https://github.com/input-output-hk/cardano-node/blob/e5b82e6ad84762ebb19ad7a60ccdc0fd8640cc20/cardano-cli/src/Cardano/CLI/Shelley/Run/Query.hs
* https://github.com/input-output-hk/cardano-node/blob/17bbfb7568a6825c1ea18957a84aa34840860e32/cardano-api/src/Cardano/Api/Query.hs
* https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-consensus/src/Ouroboros/Consensus/Ledger/Query.hs
* https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-consensus-shelley/src/Ouroboros/Consensus/Shelley/Ledger/Query.hs
